development:
  password:
  theme_id: ""
  store: frye-prod.myshopify.com

staging:
  password:
  theme_id: "138372350229"
  store: frye-prod.myshopify.com

production:
  password:
  theme_id: "138368549141"
  store: frye-prod.myshopify.com
